# Generated by Django 5.2.6 on 2025-10-12 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品编码')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='客户ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('reg_date', models.DateField(verbose_name='注册日期')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
                'indexes': [models.Index(fields=['phone'], name='idx_customer_phone')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('已发货', '已发货'), ('已完成', '已完成')], max_length=10, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='订单总金额')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'shop_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='明细ID')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.order', verbose_name='订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'shop_order_item',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='关联ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.category', verbose_name='分类')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品-分类关联',
                'verbose_name_plural': '商品-分类关联',
                'db_table': 'product_category',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(through='core.ProductCategory', through_fields=('product', 'category'), to='core.category', verbose_name='关联分类'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('path', models.CharField(max_length=255, verbose_name='访问路径')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.FloatField(verbose_name='访问耗时（秒）')),
                ('ip', models.CharField(max_length=50, verbose_name='访问IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='访问用户')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
                'db_table': 'access_logs',
                'indexes': [models.Index(fields=['user', 'start_time'], name='idx_log_user')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_code'], name='idx_order_code'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='idx_order_item'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('product', 'category'), name='uk_prod_cat'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='idx_product_code'),
        ),
    ]
